tap 'caskroom/fonts'
tap 'heroku/brew'
tap 'homebrew/bundle'
tap 'thoughtbot/formulae'

brew 'azure-cli'
brew 'elixir'
brew 'heroku'
brew 'libffi'
brew 'libyaml'
brew 'node'
brew 'onepass'
brew 'openssl'
brew 'postgres', restart_service: true
brew 'rcm'
brew 'redis', restart_service: true
brew 'terraform'
brew 'tmux'
brew 'vim'
brew 'wget'
brew 'yarn'
brew 'zsh'

cask '1password'
cask 'box-sync'
cask 'dotnet'
cask 'dotnet-sdk'
cask 'slack'
cask 'tower'
cask 'transmit'

cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'font-source-serif-pro'
